site_name: Amazon EKS Blueprints Quick Start
repo_name: "aws-quickstart/cdk-eks-blueprints"
repo_url: "https://github.com/aws-quickstart/cdk-eks-blueprints"
docs_dir: "docs"
theme: 
  name: material
  features: 
    - tabs
nav:
  - Overview: 'index.md'
  - Getting Started: 'getting-started.md'
  - Core Concepts: 'core-concepts.md'
  - Teams: 'teams.md'
  - Pipelines: 'pipelines.md'
  - AddOns:
    - Overview: 'addons/index.md'
    - AWS App Mesh: 'addons/app-mesh.md'
    - ArgoCD: 'addons/argo-cd.md'
    - AWS For Fluent Bit: 'addons/aws-for-fluent-bit.md'
    - AWS Load Balancer Controller: 'addons/aws-load-balancer-controller.md'
    - AWS Node Termination Handler: 'addons/aws-node-termination-handler.md'
    - Calico: 'addons/calico.md'
    - Cluster Autoscaler: 'addons/cluster-autoscaler.md'
    - Container Insights: 'addons/container-insights.md'
    - CoreDns: 'addons/coredns.md'
    - EBS CSI Driver: 'addons/ebs-csi-driver.md'
    - EFS CSI Driver: 'addons/efs-csi-driver.md'
    - External DNS: 'addons/external-dns.md'
    - Karpenter: 'addons/karpenter.md'
    - Kube Proxy: 'addons/kube-proxy.md'
    - Kubecost: 'addons/kubecost.md'
    - Kubevious: 'addons/kubevious.md'
    - Metrics Server: 'addons/metrics-server.md'
    - Nginx: 'addons/nginx.md'
    - OPA Gatekeeper: 'addons/opa-gatekeeper.md'
    - Secrets Store: 'addons/secrets-store.md'
    - SSM Agent: 'addons/ssm-agent.md'
    - Velero: 'addons/velero.md'
    - Vpc Cni: 'addons/vpc-cni.md'
    - Weave GitOps: 'https://github.com/weaveworks/weave-gitops-ssp-addon'
    - AWS XRay: 'addons/xray.md'
  - Cluster Providers: 
    - Overview: 'cluster-providers/index.md'
    - ASG Cluster Provider: 'cluster-providers/asg-cluster-provider.md'
    - MNG Cluster Provider: 'cluster-providers/mng-cluster-provider.md'
    - Fargate Cluster Provider: 'cluster-providers/fargate-cluster-provider.md'
  - Extensibility: 'extensibility.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight  
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search