site_name: Amazon EKS SSP
repo_name: "aws-quickstart/quickstart-ssp-amazon-eks"
repo_url: "https://github.com/aws-quickstart/quickstart-ssp-amazon-eks"
docs_dir: "docs"
theme: 
  name: material
  features: 
    - tabs
nav:
  - Overview: 'index.md'
  - Getting started: 'getting-started.md'
  - Core concepts: 'core-concepts.md'
  - Teams: 'teams.md'
  - Pipelines: 'pipelines.md'
  - Add-ons:
    - Overview: 'addons/index.md'
    - AWS App Mesh: 'addons/app-mesh.md'
    - Argo CD: 'addons/argo-cd.md'
    - AWS Load Balancer Controller: 'addons/aws-load-balancer-controller.md'
    - Calico: 'addons/calico.md'
    - Cluster Autoscaler: 'addons/cluster-autoscaler.md'
    - Container Insights: 'addons/container-insights.md'
    - ExternalDNS: 'addons/external-dns.md'
    - Metrics Server: 'addons/metrics-server.md'
    - NGINX: 'addons/nginx.md'
    - SSM Agent: 'addons/ssm-agent.md'
    - Weave GitOps: 'https://github.com/weaveworks/weave-gitops-ssp-addon'
    - AWS X-Ray: 'addons/xray.md'
  - Cluster providers: 
    - Overview: 'cluster-providers/index.md'
    - EC2 cluster provider: 'cluster-providers/ec2-cluster-provider.md'
  - Advanced:
    - Multicluster management: 'advanced/multi-cluster-management.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight  
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search