---
blank_issues_enabled: false
contact_links:
  - name: Reporting a Vulnerability
    url: https://github.com/aws-quickstart/cdk-eks-blueprints/security/policy
    about: Please report security vulnerabilities here.