version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
  build:
    commands:
      - npm install aws-cdk@1.104.0 -g
      - npm install
      - cdk deploy -a "npx ts-node examples/blueprint-construct/index.ts" --all --require-approval never
    finally:
      - cdk destroy -a "npx ts-node examples/blueprint-construct/index.ts" --all --force
cache:
  paths:
    - 'node_modules/**/*' 