version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
  build:
    commands:
      - npm install aws-cdk@1.104.0 -g
      - npm install
artifacts:
  files: '**/*'
cache:
  paths:
    - 'node_modules/**/*' 